/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telephonedirectory;
import java.sql.*;
import telephone_models.MyLib;
/**
 *
 * @author Pranjal
 */
public class ShowAdmin extends javax.swing.JFrame {

    /**
     * Creates new form ShowAdmin
     */
    public ShowAdmin() {
        initComponents();
        setSize(1200,1200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ShowButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        CancelButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel1.setText("EDIT ADMIN DETAILS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 20, 330, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setText("NAME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 90, 130, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setText("FATHER NAME");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 150, 150, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setText("ADDRESS");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 210, 130, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setText("CITY");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 280, 130, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel6.setText("STATE");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 350, 130, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel7.setText("PIN CODE");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 420, 130, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel8.setText("CONTACT");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 480, 120, 50);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel9.setText("EMAIL");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(50, 540, 100, 60);

        ShowButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ShowButton.setText("SHOW");
        ShowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ShowButton);
        ShowButton.setBounds(590, 100, 140, 50);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(230, 90, 310, 40);

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextField2);
        jTextField2.setBounds(230, 150, 310, 40);

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextField4);
        jTextField4.setBounds(230, 280, 310, 40);

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextField5);
        jTextField5.setBounds(230, 350, 310, 40);

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextField6);
        jTextField6.setBounds(230, 420, 310, 40);

        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextField7);
        jTextField7.setBounds(230, 480, 310, 40);

        jTextField8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8);
        jTextField8.setBounds(230, 550, 310, 40);

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        getContentPane().add(jTextField3);
        jTextField3.setBounds(230, 210, 310, 40);

        CancelButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        CancelButton.setText("CANCEL");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CancelButton);
        CancelButton.setBounds(590, 360, 140, 50);

        DeleteButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        DeleteButton.setText("DELETE");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteButton);
        DeleteButton.setBounds(590, 280, 140, 50);

        UpdateButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        UpdateButton.setText("UPDATE");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateButton);
        UpdateButton.setBounds(590, 190, 140, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ShowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowButtonActionPerformed
        //code to show data of related email
        try
        {
            MyLib obj = new MyLib();
            Connection cn=obj.create_connection();
            //instead of making 2 queries we extract data from view
            //String s1="select * from admindata where email=?";
            //String s2="select * from logindata where email=?";
            String sql="select * from admindata where email=?";
            PreparedStatement p1=cn.prepareStatement(sql);
            p1.setString(1, jTextField8.getText().trim());
            ResultSet rs=p1.executeQuery();
            if(rs.next())
            {
                String id,name,father,address,contact,city,state,pincode,email;
                id=rs.getString("id");
                name=rs.getString("name");
                father=rs.getString("father");
                address=rs.getString("address");
                contact=rs.getString("contact");
                city=rs.getString("city");
                state=rs.getString("state");
                pincode=rs.getString("pincode");
                email=rs.getString("email");

                //setting values according to email
                jTextField1.setText(name);
                jTextField2.setText(father);
                jTextField3.setText(address);
                jTextField4.setText(city);
                jTextField5.setText(state);
                jTextField6.setText(pincode);
                jTextField7.setText(contact);
                jTextField8.setText(email);

                //allowing buttons
                DeleteButton.setEnabled(true);
                UpdateButton.setEnabled(true);
                CancelButton.setEnabled(true);
                ShowButton.setEnabled(false);

                //setting editable and noneditable fields
                jTextField1.setEnabled(true);
                jTextField2.setEnabled(true);
                jTextField3.setEnabled(true);
                jTextField4.setEnabled(true);
                jTextField5.setEnabled(true);
                jTextField6.setEnabled(true);
                jTextField7.setEnabled(true);
                jTextField8.setEditable(false);
            }

        }
        catch(Exception e)
        {
            javax.swing.JOptionPane.showMessageDialog(null, ""+e);
        }
    }//GEN-LAST:event_ShowButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        //Form will not have Cancel,Delete and Show button opened
        CancelButton.setEnabled(false);
        DeleteButton.setEnabled(false);
        ShowButton.setEnabled(false);

        //also disallowing other text fields
        jTextField1.setEnabled(false);
        jTextField2.setEnabled(false);
        jTextField3.setEnabled(false);
        jTextField4.setEnabled(false);
        jTextField5.setEnabled(false);
                jTextField6.setEnabled(false);

        jTextField7.setEnabled(false);
        jTextField8.setEnabled(false);

        // what todo when cancel clearing all input fields
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");

        //enabling show button
        ShowButton.setEnabled(true);
        jTextField8.setEditable(true);
        jTextField8.requestFocus();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // Code to delete
        try
        {
            MyLib obj = new MyLib();
            Connection cn=obj.create_connection();
            String sql="delete from admindata where email=?";
            PreparedStatement p1=cn.prepareStatement(sql);
            p1.setString(1, jTextField8.getText().trim());
            int a=p1.executeUpdate();
            if(a==1)
            {
                javax.swing.JOptionPane.showMessageDialog(null, "Data Deleted");
            }
        }
        catch(Exception e)
        {
            javax.swing.JOptionPane.showMessageDialog(null, ""+e);
        }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        //udpate button
        try
        {
            MyLib obj = new MyLib();
            Connection cn=obj.create_connection();
            String s1="update admindata set name=?,father=?,address=?,city=?,state=?,pincode=?,contact=? where email=?";
            String s2="update logindata set password=? where email=?";
            PreparedStatement p1=cn.prepareStatement(s1);
            PreparedStatement p2=cn.prepareStatement(s2);
            //replacing ? with textfields values
            p1.setString(1, jTextField1.getText().trim());
            p1.setString(2, jTextField2.getText().trim());
            p1.setString(3, jTextField3.getText().trim());
            p1.setString(4, jTextField4.getText().trim());
            p1.setString(5, jTextField5.getText().trim());
            p1.setString(6, jTextField6.getText().trim());
            p1.setString(7, jTextField7.getText().trim());
            p1.setString(8, jTextField8.getText().trim());

            p2.setString(2, jTextField8.getText().trim());

            int a =p1.executeUpdate();
            int b=p2.executeUpdate();

            if(a==1 && b==1)
            {
                javax.swing.JOptionPane.showMessageDialog(null, "Data Updated");
            }
            else
            {
                javax.swing.JOptionPane.showMessageDialog(null, "Data not Updated");
            }
        }
        catch(Exception e)
        {
            javax.swing.JOptionPane.showMessageDialog(null, ""+e);
        }
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton ShowButton;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
