/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telephone_panels;
import java.sql.*;
import telephone_models.MyLib;
/**
 *
 * @author Pranjal
 */
public class Edituserdata extends javax.swing.JPanel {

    /**
     * Creates new form Edituserdata1
     */
    public Edituserdata() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        UpdateButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        CancelButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        ShowButton = new javax.swing.JButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel1.setText("EDIT USER DATA");
        add(jLabel1);
        jLabel1.setBounds(370, 10, 200, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("FIRST NAME");
        add(jLabel2);
        jLabel2.setBounds(30, 60, 120, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("LAST NAME");
        add(jLabel3);
        jLabel3.setBounds(30, 130, 110, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("FATHER");
        add(jLabel4);
        jLabel4.setBounds(30, 200, 80, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("ADDRESS");
        add(jLabel5);
        jLabel5.setBounds(30, 270, 100, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("CITY");
        add(jLabel6);
        jLabel6.setBounds(30, 340, 80, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("STATE");
        add(jLabel7);
        jLabel7.setBounds(30, 410, 80, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("PINCODE");
        add(jLabel8);
        jLabel8.setBounds(490, 60, 120, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("CONTACT");
        add(jLabel9);
        jLabel9.setBounds(490, 130, 120, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setText("EMAIL");
        add(jLabel10);
        jLabel10.setBounds(490, 200, 110, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setText("PASSWORD");
        add(jLabel11);
        jLabel11.setBounds(490, 260, 160, 40);

        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadioButton1.setText("MALE");
        add(jRadioButton1);
        jRadioButton1.setBounds(610, 330, 110, 50);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setText("GENDER");
        add(jLabel12);
        jLabel12.setBounds(490, 330, 110, 40);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel13.setText("MARRIGE ST.");
        add(jLabel13);
        jLabel13.setBounds(490, 410, 140, 40);

        jRadioButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadioButton3.setText("MARRIED");
        add(jRadioButton3);
        jRadioButton3.setBounds(610, 410, 140, 50);

        UpdateButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        UpdateButton.setText("UPDATE");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });
        add(UpdateButton);
        UpdateButton.setBounds(20, 480, 180, 80);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        add(jTextField1);
        jTextField1.setBounds(190, 60, 250, 40);

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        add(jTextField2);
        jTextField2.setBounds(190, 130, 250, 40);

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        add(jTextField3);
        jTextField3.setBounds(190, 200, 250, 40);

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        add(jTextField4);
        jTextField4.setBounds(190, 270, 250, 40);

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        add(jTextField5);
        jTextField5.setBounds(190, 340, 250, 40);

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        add(jTextField6);
        jTextField6.setBounds(190, 410, 250, 40);

        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        add(jTextField7);
        jTextField7.setBounds(600, 60, 260, 40);

        jTextField8.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        add(jTextField8);
        jTextField8.setBounds(600, 130, 260, 40);

        jTextField9.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        add(jTextField9);
        jTextField9.setBounds(600, 200, 260, 40);

        jTextField10.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        add(jTextField10);
        jTextField10.setBounds(600, 260, 260, 40);

        CancelButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        CancelButton.setText("CANCEL");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });
        add(CancelButton);
        CancelButton.setBounds(720, 480, 180, 80);

        DeleteButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        DeleteButton.setText("DELETE");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });
        add(DeleteButton);
        DeleteButton.setBounds(520, 480, 180, 80);

        ShowButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        ShowButton.setText("SHOW");
        ShowButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ShowButton.setMaximumSize(new java.awt.Dimension(113, 33));
        ShowButton.setMinimumSize(new java.awt.Dimension(113, 33));
        ShowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowButtonActionPerformed(evt);
            }
        });
        add(ShowButton);
        ShowButton.setBounds(270, 480, 210, 80);

        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadioButton2.setText("FEMALE");
        add(jRadioButton2);
        jRadioButton2.setBounds(770, 340, 100, 31);

        jRadioButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadioButton4.setText("UNMARRIED");
        add(jRadioButton4);
        jRadioButton4.setBounds(780, 420, 140, 31);
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        //udpate button
        try
        {
            MyLib obj = new MyLib();
            Connection cn=obj.create_connection();
            String s1="update userdata set fname=?,lname=?,father=?,address=?,city=?,state=?,pincode=?,contact=? where email=?";
            String s2="update logindata set password=? where email=?";
            PreparedStatement p1=cn.prepareStatement(s1);
            PreparedStatement p2=cn.prepareStatement(s2);
            //replacing ? with textfields values
            p1.setString(1, jTextField1.getText().trim());
            p1.setString(2, jTextField2.getText().trim());
            p1.setString(3, jTextField3.getText().trim());
            p1.setString(4, jTextField4.getText().trim());
            p1.setString(5, jTextField5.getText().trim());
            p1.setString(6, jTextField6.getText().trim());
            p1.setString(7, jTextField7.getText().trim());
            p1.setString(8, jTextField8.getText().trim());
            p1.setString(9, jTextField9.getText().trim());

            p2.setString(1, jTextField10.getText().trim());
            p2.setString(2, jTextField9.getText().trim());

            int a =p1.executeUpdate();
            int b=p2.executeUpdate();

            if(a==1 && b==1)
            {
                javax.swing.JOptionPane.showMessageDialog(null, "Data Updated");
            }
            else
            {
                javax.swing.JOptionPane.showMessageDialog(null, "Data not Updated");
            }
        }
        catch(Exception e)
        {
            javax.swing.JOptionPane.showMessageDialog(null, ""+e);
        }
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        //Form will not have Cancel,Delete and Show button opened
        CancelButton.setEnabled(false);
        DeleteButton.setEnabled(false);
        ShowButton.setEnabled(false);

        //also disallowing other text fields
        jTextField1.setEnabled(false);
        jTextField2.setEnabled(false);
        jTextField3.setEnabled(false);
        jTextField4.setEnabled(false);
        jTextField5.setEnabled(false);
        jTextField6.setEnabled(false);
        jTextField7.setEnabled(false);
        jTextField8.setEnabled(false);
        jTextField10.setEnabled(false);

        // what todo when cancel clearing all input fields
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jTextField10.setText("");

        //enabling show button
        ShowButton.setEnabled(true);
        jTextField9.setEditable(true);
        jTextField9.requestFocus();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // Code to delete
        try
        {
            MyLib obj = new MyLib();
            Connection cn=obj.create_connection();
            String sql="delete from userdata where email=?";
            PreparedStatement p1=cn.prepareStatement(sql);
            p1.setString(1, jTextField9.getText().trim());
            int a=p1.executeUpdate();
            if(a==1)
            {
                javax.swing.JOptionPane.showMessageDialog(null, "Data Deleted");
            }
        }
        catch(Exception e)
        {
            javax.swing.JOptionPane.showMessageDialog(null, ""+e);
        }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void ShowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowButtonActionPerformed
        //code to show data of related email
        try
        {
            MyLib obj = new MyLib();
            Connection cn=obj.create_connection();
            String sql="select * from userdata where email=?";
            PreparedStatement p1=cn.prepareStatement(sql);
            p1.setString(1, jTextField9.getText().trim());
            javax.swing.JOptionPane.showMessageDialog(null, "Email : "+jTextField9.getText().trim());
            ResultSet rs=p1.executeQuery();
            if(rs.next())
            {
                javax.swing.JOptionPane.showMessageDialog(null,"Found");
                String id,fname,lname,father,address,contact,city,state,pincode,email,password;
                id=rs.getString("id");
                fname=rs.getString("fname");
                lname=rs.getString("lname");
                father=rs.getString("father");
                address=rs.getString("address");
                contact=rs.getString("contact");
                city=rs.getString("city");
                state=rs.getString("state");
                pincode=rs.getString("pincode");
                email=rs.getString("email");
                password=rs.getString("password");

                //setting values according to email
                jTextField1.setText(fname);
                jTextField2.setText(lname);
                jTextField3.setText(father);
                jTextField4.setText(address);
                jTextField5.setText(city);
                jTextField6.setText(state);
                jTextField7.setText(pincode);
                jTextField8.setText(contact);
                jTextField9.setText(email);
                jTextField10.setText(password);

                //allowing buttons
                DeleteButton.setEnabled(true);
                UpdateButton.setEnabled(true);
                CancelButton.setEnabled(true);
                ShowButton.setEnabled(false);

                //setting editable and noneditable fields
                jTextField1.setEnabled(true);
                jTextField2.setEnabled(true);
                jTextField3.setEnabled(true);
                jTextField4.setEnabled(true);
                jTextField5.setEnabled(true);
                jTextField6.setEnabled(true);
                jTextField7.setEnabled(true);
                jTextField8.setEnabled(true);
                jTextField9.setEditable(false);
                jTextField10.setEnabled(true);
            }

        }
        catch(Exception e)
        {
            javax.swing.JOptionPane.showMessageDialog(null, ""+e);
        }
    }//GEN-LAST:event_ShowButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JButton DeleteButton;
    javax.swing.JButton ShowButton;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
